### PR TITLE
18 hangman 18 20

### LINKED ISSUE #42: 18 - Hangman-18
This will be your final hangman issue.

Using the knowledge you've gathered during these past weeks, improve your code/user experience however you want to.

- Improve code and/or user experience
- Add features if you want. If you're adding functionality, explain what it does in the PR description
- Feel free to use external packages
- Clean up your code; remove redundant print statements

### PR DESCRIPTION
**Pull request by ebosetalee**
Resolves #42 [https://repl.it/join/hwurcxjd-emmanuellaesezo](https://repl.it/join/hwurcxjd-emmanuellaesezo)
[https://repl.it/@EmmanuellaEsezo/18-Hangman-18-20](https://repl.it/@EmmanuellaEsezo/18-Hangman-18-20)

I added a new file called design.py to the lib folder which contains the introduction and the beautiful text so the main.py calls the function in design.py. The intention was to use player 1 or 2 so the introduction doesn't print more than once for a person but since its a one player game, no need. 
I edited readme.md to explain the contents of the challenge. 

I looked at the code over again and i couldn't figure out what needs changing. Thank you.

### CODE REVIEW

**Review by jirevwe — APPROVED** [review]

**Comment by mykeels** [comment]
Yo! How can I play this game?

**Comment by ebosetalee** [comment]
@mykeels click on the [replit.it link](https://repl.it/@EmmanuellaEsezo/18-Hangman-18-20)

**Review by yudori — APPROVED** [review]
Looks good @ebosetalee . Well done 👍

**Comment by yudori** [comment]
@ebosetalee you'll need to take out the commits from 3 days ago before I can merge
image

image

**Comment by ebosetalee** [comment]
@yudori  how do i remove it

**Comment by mykeels** [comment]
Love it!

image

**Pull request merged**
